# Based on mob-sakai and YarnSpinnerTool action
# Secrets
#   UNITY_LICENSE:
name: Run Tests 🧪

on: 
  push:
      branches:
          - main
          - develop
          #- 'feature/**'
      paths:
        - 'Editor/**'
        - 'Runtime/**'
        - 'Samples~/**'
        - 'Tests/**'
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  buildAndTestForSomePlatforms:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      # Run tests
      - name: "Run tests"
        id: runTests
        uses: trudeaua21/unity-test-runner@main
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectPath: "."
          unityVersion: "2020.3.0f1"
          testMode: all
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+open-source-unity-package.test-package.*,-*Tests*'
          packageMode: true
      
      # Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results (edit + play, ${{ matrix.unityVersion }}-${{ matrix.targetPlatform }}
          path: ${{ steps.testRunner.outputs.artifactsPath }}

      # Upload coverage
      - name: Upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: Package Coverage results (all)
          path: ${{ steps.runTests.outputs.coveragePath }}
          retention-days: 1