# Based on mob-sakai and YarnSpinnerTool action
# Secrets
#   UNITY_LICENSE:
name: Run Tests 🧪

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  testAllPackageModesLikeInTheReadme:
    name: Test package mode 📦 in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ./
        unityVersion:
          - 2019.2.11f1
          #- 2020.3.29f1
        testMode:
          - editmode
          #- playmode
    steps:
      ###########################
      #         Checkout        #
      ###########################
      - uses: actions/checkout@v2
        
      #######################
      #         Test        #
      #######################
      # Configure test runner
      - name: Run tests
        id: packageEditMode
        uses: trudeaua21/unity-test-runner@main
        env:
          # Personal license
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-packageArtifacts
          packageMode: true
          
      #############################
      #         Debug repo        #
      #############################
      - run: ls -la
        # Execute even if the previous step failed
        if: always()
        working-directory: ${{ github.workspace }}/${{ matrix.testMode }}-packageArtifacts

      #############################
      #   Upload artifacts        #
      #############################
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: Package test results (${{ matrix.testMode }})
          path: ${{ steps.packageEditMode.outputs.artifactsPath }}
          retention-days: 14
